[global]
log_level = 'error'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 20
clear_on_start = true
tx_confirmation = false

[rest]
enabled = false
host = '127.0.0.1'
port = 3000

[telemetry]
enabled = true
host = '0.0.0.0'
port = 3001

[[chains]]
id = "coreum-mainnet-1"
type = "CosmosSdk"
rpc_addr = 'http://tasks.lb_coreum:8000'
grpc_addr = 'http://tasks.lb_coreum:8003'
rpc_timeout = "30s"
trusted_node = false
account_prefix = "core"
key_name = "coreum"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 300000
max_gas = 10000000
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
clock_drift = "40s"
max_block_time = "10s"
trusting_period = '32hours'
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false
compat_mode = '0.37'
event_source = { mode = 'push', url = 'ws://tasks.lb_coreum:8000/websocket', batch_delay = '500ms' }
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 0.0625, denom = 'ucore' }
address_type = { derivation = 'cosmos' }

[chains.packet_filter]
policy = "allow"
list = [
    # ['transfer', 'channel-0'], # osmosis
    # ['transfer', 'channel-1'], # osmosis
    ['transfer', 'channel-2'], # osmosis
    # ['transfer', 'channel-4'], # cosmoshub
    # ['transfer', 'channel-5'], # cosmoshub
    ['transfer', 'channel-9'], # cosmoshub
    # ['transfer', 'channel-3'], # axelar
    ['transfer', 'channel-6'], # axelar
    ['transfer', 'channel-8'], # evmos
    ['transfer', 'channel-7'], # gravitybridge
    ['transfer', 'channel-18'], # kava
    # ['transfer', 'channel-12'], # secret
    # ['transfer', 'channel-12'], # secret
    ['transfer', 'channel-25'], # secret
    ['transfer', 'channel-19'], # noble
    ['transfer', 'channel-17'], # kujira
    ['transfer', 'channel-20'], # bandchain
    ['transfer', 'channel-24'], # dydx
    ['transfer', 'channel-26'], # sei
]

[chains.packet_filter.min_fees]

[[chains]]
id = "osmosis-1"
type = "CosmosSdk"
rpc_addr = 'http://tasks.lb_osmosis:8000'
grpc_addr = 'http://tasks.lb_osmosis:8003'
rpc_timeout = "30s"
trusted_node = false
account_prefix = "osmo"
key_name = "osmosis"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 300000
max_gas = 20000000
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
clock_drift = "100s"
max_block_time = "10s"
trusting_period = '224hours'
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false
compat_mode = '0.37'
event_source = { mode = 'push', url = 'ws://tasks.lb_osmosis:8000/websocket', batch_delay = '500ms' }
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 0.003, denom = 'uosmo' }
address_type = { derivation = 'cosmos' }

[chains.packet_filter]
policy = "allow"
list = [
    # ['transfer', 'channel-2169'], # coreum
    # ['transfer', 'channel-2187'], # coreum
    ['transfer', 'channel-2188'], # coreum
]

[[chains]]
id = "cosmoshub-4"
type = "CosmosSdk"
rpc_addr = 'http://tasks.lb_cosmoshub:8000'
grpc_addr = 'http://tasks.lb_cosmoshub:8003'
rpc_timeout = "30s"
trusted_node = false
account_prefix = "cosmos"
key_name = "cosmoshub"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 180000
max_gas = 2500000
gas_multiplier = 2
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
clock_drift = "1000s"
max_block_time = "10s"
trusting_period = '14days'
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false
compat_mode = '0.34'
event_source = { mode = 'push', url = 'ws://tasks.lb_cosmoshub:8000/websocket', batch_delay = '500ms' }
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 0.01, denom = 'uatom' }
address_type = { derivation = 'cosmos' }

[chains.packet_filter]
policy = "allow"
list = [
    # ['transfer', 'channel-653'], # coreum
    # ['transfer', 'channel-654'], # coreum
    ['transfer', 'channel-660'], # coreum
]

[[chains]]
id = "axelar-dojo-1"
type = "CosmosSdk"
rpc_addr = 'http://tasks.lb_axelar:8000'
grpc_addr = 'http://tasks.lb_axelar:8003'
rpc_timeout = "15s"
trusted_node = false
account_prefix = "axelar"
key_name = "axelar"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 100000
max_gas = 4000000
gas_multiplier = 2
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
clock_drift = "50s"
max_block_time = "10s"
trusting_period = '112hours'
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false
compat_mode = '0.34'
event_source = { mode = 'push', url = 'ws://tasks.lb_axelar:8000/websocket', batch_delay = '500ms' }
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 0.0075, denom = 'uaxl' }
address_type = { derivation = 'cosmos' }

[chains.packet_filter]
policy = "allow"
list = [
    # ['transfer', 'channel-119'], # coreum
    ['transfer', 'channel-120'], # coreum
]

[[chains]]
id = "evmos_9001-2"
type = "CosmosSdk"
rpc_addr = 'http://tasks.lb_evmos:8000'
grpc_addr = 'http://tasks.lb_evmos:8003'
rpc_timeout = "30s"
trusted_node = false
account_prefix = "evmos"
key_name = "evmos"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 180000
max_gas = 2500000
gas_multiplier = 2
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
clock_drift = "40s"
max_block_time = "10s"
trusting_period = '224hours'
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false
event_source = { mode = 'push', url = 'ws://tasks.lb_evmos:8000/websocket', batch_delay = '500ms' }
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 0.0075, denom = 'aevmos' }
address_type = { derivation = 'ethermint', proto_type = { pk_type = '/ethermint.crypto.v1.ethsecp256k1.PubKey' } }
compat_mode = '0.37'

[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-87'], # coreum
]

[[chains]]
id = "gravity-bridge-3"
type = "CosmosSdk"
rpc_addr = 'http://tasks.lb_gravitybridge:8000'
grpc_addr = 'http://tasks.lb_gravitybridge:8003'
rpc_timeout = "20s"
trusted_node = false
account_prefix = "gravity"
key_name = "gravitybridge"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 300000
max_gas = 10000000
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
clock_drift = "40s"
max_block_time = "10s"
trusting_period = '32hours'
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false
event_source = { mode = 'push', url = 'ws://tasks.lb_gravitybridge:8000/websocket', batch_delay = '500ms' }
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 0.0025, denom = 'ugraviton' }
address_type = { derivation = 'cosmos' }
compat_mode = '0.34'
[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-142'], # coreum
]

[[chains]]
id = "kava_2222-10"
type = "CosmosSdk"
rpc_addr = 'http://tasks.lb_kava:8000'
grpc_addr = 'http://tasks.lb_kava:8003'
rpc_timeout = "20s"
trusted_node = false
account_prefix = "kava"
key_name = "kava"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 300000
max_gas = 10000000
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
clock_drift = "40s"
max_block_time = "10s"
trusting_period = '14days'
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false
event_source = { mode = 'push', url = 'ws://tasks.lb_kava:8000/websocket', batch_delay = '500ms' }
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 0.0025, denom = 'ukava' }
address_type = { derivation = 'cosmos' }
compat_mode = '0.34'
[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-142'], # coreum
]

[[chains]]
id = "secret-4"
type = "CosmosSdk"
rpc_addr = 'https://secret-4.api.trivium.network:26657'
grpc_addr = 'https://secretnetwork-grpc.lavenderfive.com:443'
#rpc_addr = 'https://rpc-secret.whispernode.com:443'
#grpc_addr = 'https://secretnetwork-grpc.lavenderfive.com:443'
#websocket_addr = 'wss://rpc-secret.whispernode.com:443/websocket'
rpc_timeout = "20s"
trusted_node = false
account_prefix = "secret"
key_name = "secret"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 300000
max_gas = 10000000
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
clock_drift = "40s"
max_block_time = "10s"
trusting_period = '224hours'
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false
event_source = { mode = 'push', url = 'wss://secret-4.api.trivium.network:26657/websocket', batch_delay = '500ms' }
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 0.1, denom = 'uscrt' }
address_type = { derivation = 'cosmos' }
compat_mode = '0.34'
[chains.packet_filter]
policy = "allow"
list = [
    # ['transfer', 'channel-92'], # coreum
    # ['transfer', 'channel-99'], # coreum
    ['transfer', 'channel-101'], # coreum
]

[[chains]]
id = "noble-1"
type = "CosmosSdk"
rpc_addr = 'http://tasks.lb_noble:8000'
grpc_addr = 'http://tasks.lb_noble:8003'
rpc_timeout = "20s"
trusted_node = false
account_prefix = "noble"
key_name = "noble"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 300000
max_gas = 10000000
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
clock_drift = "40s"
max_block_time = "10s"
trusting_period = '14days'
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false
event_source = { mode = 'push', url = 'ws://tasks.lb_noble:8000/websocket', batch_delay = '500ms' }
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 0.0, denom = 'uusdc' }
address_type = { derivation = 'cosmos' }
compat_mode = '0.34'
[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-49'], # coreum
]

[[chains]]
id = "kaiyo-1"
type = "CosmosSdk"
rpc_addr = 'http://tasks.lb_kujira:8000'
grpc_addr = 'http://tasks.lb_kujira:8003'
rpc_timeout = "20s"
trusted_node = false
account_prefix = "kujira"
key_name = "noble"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 300000
max_gas = 10000000
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
clock_drift = "40s"
max_block_time = "10s"
trusting_period = '14days'
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false
event_source = { mode = 'push', url = 'ws://tasks.lb_kujira:8000/websocket', batch_delay = '500ms' }
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 0.01, denom = 'ukuji' }
address_type = { derivation = 'cosmos' }
compat_mode = '0.37'
[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-122'],
]

[[chains]]
id = "laozi-mainnet"
type = "CosmosSdk"
rpc_addr = 'http://rpc.laozi1.bandchain.org:80'
grpc_addr = 'http://grpc-band-01.stakeflow.io:2502/'
rpc_timeout = "20s"
trusted_node = false
account_prefix = "band"
key_name = "bandchain"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 300000
max_gas = 10000000
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
clock_drift = "40s"
max_block_time = "10s"
trusting_period = '32hours'
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false
event_source = { mode = 'push', url = 'ws://rpc.laozi1.bandchain.org:80/websocket', batch_delay = '500ms' }
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 0.0025, denom = 'uband' }
address_type = { derivation = 'cosmos' }
compat_mode = '0.34'
[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-159'],
]

[[chains]]
id = "dydx-mainnet-1"
type = "CosmosSdk"
rpc_addr = 'http://tasks.lb_dydx:8000'
grpc_addr = 'http://tasks.lb_dydx:8003'
rpc_timeout = "20s"
trusted_node = false
account_prefix = "dydx"
key_name = "dydx"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 300000
max_gas = 10000000
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
clock_drift = "40s"
max_block_time = "10s"
trusting_period = '32hours'
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false
event_source = { mode = 'push', url = 'ws://tasks.lb_dydx:8000/websocket', batch_delay = '500ms' }
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 12500000000, denom = 'adydx' }
address_type = { derivation = 'cosmos' }
compat_mode = '0.37'
[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-14'], # coreum
]

[[chains]]
id = "pacific-1"
type = "CosmosSdk"
rpc_addr = 'http://tasks.lb_sei:8000'
grpc_addr = 'http://tasks.lb_sei:8003'
rpc_timeout = "10s"
trusted_node = false
account_prefix = "sei"
key_name = "sei-2"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 100000
max_gas = 400000
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
clock_drift = "5s"
max_block_time = "30s"
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false
compat_mode = '0.37'
event_source = { mode = 'push', url = 'ws://tasks.lb_sei:8000/websocket', batch_delay = '500ms' }
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 0.1, denom = 'usei' }
address_type = { derivation = 'cosmos' }
[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-47'], # coreum
]
