[global]
log_level = "error"

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = false
auto_register_counterparty_payee = false

[rest]
enabled = false
host = "127.0.0.1"
port = 3000

[telemetry]
enabled = true
host = '0.0.0.0'
port = 3001

[telemetry.buckets.latency_submitted]
start = 500
end = 20000
buckets = 10

[telemetry.buckets.latency_confirmed]
start = 1000
end = 30000
buckets = 10

[[chains]]
id = "cosmoshub-4"
type = "CosmosSdk"
rpc_addr = "http://tasks.lb_cosmoshub:8000"
grpc_addr = "http://tasks.lb_cosmoshub:8003"
rpc_timeout = "10s"
trusted_node = false
account_prefix = "cosmos"
key_name = "cosmoshub"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 100000
max_gas = 400000
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
clock_drift = "5s"
max_block_time = "30s"
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false
event_source = { mode = 'push', url = 'ws://tasks.lb_cosmoshub:8000/websocket', batch_delay = '500ms' }
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 0.025, denom = 'uatom' }

[chains.packet_filter]
policy = "allow"
list = [
    ["transfer", "channel-207"],
    ["transfer", "channel-536"],
    ["transfer", "channel-141"],
    ["transfer", "channel-339"],
]

[chains.packet_filter.min_fees]

[chains.address_type]
derivation = "cosmos"

[[chains]]
id = "furya-1"
type = "CosmosSdk"
rpc_addr = "http://tasks.lb_furya:8000"
grpc_addr = "http://tasks.lb_furya:8003"
rpc_timeout = "10s"
trusted_node = false
account_prefix = "furya"
key_name = "furya"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 100000
max_gas = 400000
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
clock_drift = "5s"
max_block_time = "30s"
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false
event_source = { mode = 'push', url = 'ws://tasks.lb_furya:8000/websocket', batch_delay = '500ms' }
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 0.25, denom = 'ufury' }

[chains.packet_filter]
policy = "allow"
list = [
    ["transfer", "channel-2"],
    ["transfer", "channel-3"],
    ["transfer", "channel-1"],
]

[chains.packet_filter.min_fees]

[chains.address_type]
derivation = "cosmos"

[[chains]]
id = "juno-1"
type = "CosmosSdk"
rpc_addr = "http://tasks.lb_juno:8000"
grpc_addr = "http://tasks.lb_juno:8003"
rpc_timeout = "10s"
trusted_node = false
account_prefix = "juno"
key_name = "juno"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 100000
max_gas = 400000
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
clock_drift = "5s"
max_block_time = "30s"
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false
event_source = { mode = 'push', url = 'ws://tasks.lb_juno:8000/websocket', batch_delay = '500ms' }
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 0.1, denom = 'ujuno' }

[chains.packet_filter]
policy = "allow"
list = [
    ["transfer", "channel-1"],
    ["transfer", "channel-417"],
    ["transfer", "channel-224"],
    ["transfer", "channel-0"],
    ["wasm.juno1v4887y83d6g28puzvt8cl0f3cdhd3y6y9mpysnsp3k8krdm7l6jqgm0rkn", "channel-47"],
    ["transfer", "channel-86"],
]

[chains.packet_filter.min_fees]

[chains.address_type]
derivation = "cosmos"

[[chains]]
id = "noble-1"
type = "CosmosSdk"
rpc_addr = "http://tasks.lb_noble:8000"
grpc_addr = "http://tasks.lb_noble:8003"
rpc_timeout = "10s"
trusted_node = false
account_prefix = "noble"
key_name = "noble"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 100000
max_gas = 400000
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
clock_drift = "5s"
max_block_time = "30s"
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false
event_source = { mode = 'push', url = 'ws://tasks.lb_noble:8000/websocket', batch_delay = '500ms' }
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 0.1, denom = 'ustake' }

[chains.packet_filter]
policy = "allowall"

[chains.packet_filter.min_fees]

[chains.address_type]
derivation = "cosmos"

[[chains]]
id = "osmosis-1"
type = "CosmosSdk"
rpc_addr = "http://tasks.lb_osmosis:8000"
grpc_addr = "http://tasks.lb_osmosis:8003"
rpc_timeout = "10s"
trusted_node = false
account_prefix = "osmo"
key_name = "osmosis"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 100000
max_gas = 400000
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
clock_drift = "5s"
max_block_time = "30s"
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false
event_source = { mode = 'push', url = 'ws://tasks.lb_osmosis:8000/websocket', batch_delay = '500ms' }
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 0.025, denom = 'uosmo' }

[chains.packet_filter]
policy = "allow"
list = [
    ["transfer", "channel-4"],
    ["transfer", "channel-3"],
    ["transfer", "channel-1"],
    ["transfer", "channel-30"],
]

[chains.packet_filter.min_fees]

[chains.address_type]
derivation = "cosmos"

[[chains]]
id = "phoenix-1"
type = "CosmosSdk"
rpc_addr = "http://tasks.lb_terra2:8000"
grpc_addr = "http://tasks.lb_terra2:8003"
rpc_timeout = "10s"
trusted_node = false
account_prefix = "terra"
key_name = "terra2"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 100000
max_gas = 400000
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
clock_drift = "5s"
max_block_time = "30s"
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false
event_source = { mode = 'push', url = 'ws://tasks.lb_terra2:8000/websocket', batch_delay = '500ms' }
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 0.015, denom = 'uluna' }

[chains.packet_filter]
policy = "allow"
list = [
    ["transfer", "channel-0"],
    ["transfer", "channel-8690"],
    ["transfer", "channel-42"],
    ["transfer", "channel-169"],
    ["transfer", "channel-750"],
    ["transfer", "channel-251"],
    ["transfer", "channel-559"],
    ["transfer", "channel-341"],
]

[chains.packet_filter.min_fees]

[chains.address_type]
derivation = "cosmos"

[tracing_server]
enabled = false
port = 5555
