[global]
log_level = 'error'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 20
clear_on_start = true
tx_confirmation = false

[rest]
enabled = false
host = '127.0.0.1'
port = 3000

[telemetry]
enabled = true
host = '0.0.0.0'
port = 3001

[[chains]]
id = "injective-1"
type = "CosmosSdk"
rpc_addr = 'http://tasks.lb_injective:8000'
grpc_addr = 'http://tasks.lb_injective:8003'
event_source = { mode = 'push', url = 'ws://tasks.lb_injective:8000/websocket', batch_delay = '500ms' }
rpc_timeout = "30s"
trusted_node = false
account_prefix = "inj"
key_name = "injective"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 300000
max_gas = 10000000
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
clock_drift = "40s"
max_block_time = "10s"
trusting_period = '14days'
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false
compat_mode = '0.37'
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 160000000.0, denom = 'inj' }
address_type = { derivation = 'cosmos' }
# address_type = { derivation = 'ethermint', proto_type = { pk_type = '/injective.crypto.v1beta1.ethsecp256k1.PubKey' } }

[chains.packet_filter]
policy = "allow"
list = [
    # sort by chain name
    ['transfer', 'channel-177'],  # neutron
]

[chains.packet_filter.min_fees]


[[chains]]
id = "neutron-1"
type = "CosmosSdk"
rpc_addr = 'http://tasks.lb_neutron:8000'
grpc_addr = 'http://tasks.lb_neutron:8003'
event_source = { mode = 'push', url = 'ws://tasks.lb_neutron:8000/websocket', batch_delay = '500ms' }
rpc_timeout = "30s"
trusted_node = false
account_prefix = "neutron"
key_name = "neutron"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 300000
max_gas = 1000000
gas_multiplier = 1.2
max_msg_num = 20
max_tx_size = 2097152
max_grpc_decoding_size = 33554432
clock_drift = "15s"
max_block_time = "10s"
trusting_period = '13days'
ccv_consumer_chain = false
#ccv_consumer_chain = true
memo_prefix = ""
sequential_batch_tx = false
compat_mode = '0.37'
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 0.6, denom = 'untrn' }
address_type = { derivation = 'cosmos' }

[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-60'],
]