[global]
log_level = 'error'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 20
clear_on_start = true
tx_confirmation = false

[rest]
enabled = false
host = '127.0.0.1'
port = 3000

[telemetry]
enabled = true
host = '0.0.0.0'
port = 3001

[[chains]]
id = "kava_2222-10"
type = "CosmosSdk"
rpc_addr = 'http://tasks.lb_kava:8000'
grpc_addr = 'http://tasks.lb_kava:8003'
event_source = { mode = 'push', url = 'ws://tasks.lb_kava:8000/websocket', batch_delay = '500ms' }
rpc_timeout = "20s"
trusted_node = false
account_prefix = "kava"
key_name = "kava"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 100000
max_gas = 4000000
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
clock_drift = "40s"
max_block_time = "10s"
trusting_period = '14days'
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 0.001, denom = 'ukava' }
address_type = { derivation = 'cosmos' }
compat_mode = '0.34'
[chains.packet_filter]
policy = "allow"
list = [
    # sort by chain name
    ["transfer", "channel-140"], # celestia
    ["transfer", "channel-0"],   # cosmoshub-4
    ["transfer", "channel-137"], # dydx-mainnet-1
    ["transfer", "channel-136"], # neutron-1
    ["transfer", "channel-139"], # noble-1
    ["transfer", "channel-1"],   # osmosis-1
    ["transfer", "channel-129"], # phoenix-1 (terra2)
]

[chains.packet_filter.min_fees]

[[chains]]
id = "celestia"
type = "CosmosSdk"
rpc_addr = 'http://tasks.lb_celestia:8000'
grpc_addr = 'http://tasks.lb_celestia:8003'
event_source = { mode = 'push', url = 'ws://tasks.lb_celestia:8000/websocket', batch_delay = '500ms' }
rpc_timeout = "20s"
trusted_node = false
account_prefix = "celestia"
key_name = "celestia"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 1000000
max_gas = 4000000
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
clock_drift = "5s"
max_block_time = "30s"
trusting_period = '14days'
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 0.1, denom = 'utia' }
address_type = { derivation = 'cosmos' }
compat_mode = '0.34'
[chains.packet_filter]
policy = "allow"
list = [
    ["transfer", "channel-13"],
]

[[chains]]
id = "noble-1"
type = "CosmosSdk"
rpc_addr = 'http://tasks.lb_noble:8000'
grpc_addr = 'http://tasks.lb_noble:8003'
event_source = { mode = 'push', url = 'ws://tasks.lb_noble:8000/websocket', batch_delay = '500ms' }
rpc_timeout = "20s"
trusted_node = false
account_prefix = "noble"
key_name = "noble"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 300000
max_gas = 10000000
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
clock_drift = "40s"
max_block_time = "10s"
trusting_period = '14days'
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 0.0, denom = 'uusdc' }
address_type = { derivation = 'cosmos' }
compat_mode = '0.34'
[chains.packet_filter]
policy = "allow"
list = [
    ["transfer", "channel-37"],
]

[[chains]]
id = "dydx-mainnet-1"
type = "CosmosSdk"
rpc_addr = 'http://tasks.lb_dydx:8000'
grpc_addr = 'http://tasks.lb_dydx:8003'
rpc_timeout = "20s"
trusted_node = false
account_prefix = "dydx"
key_name = "dydx"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 300000
max_gas = 10000000
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
clock_drift = "40s"
max_block_time = "10s"
trusting_period = '32hours'
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false
event_source = { mode = 'push', url = 'ws://tasks.lb_dydx:8000/websocket', batch_delay = '500ms' }
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 12500000000, denom = 'adydx' }
address_type = { derivation = 'cosmos' }
compat_mode = '0.37'
[chains.packet_filter]
policy = "allow"
list = [
    ["transfer", "channel-7"],
]

[[chains]]
id = "neutron-1"
type = "CosmosSdk"
rpc_addr = 'http://tasks.lb_neutron:8000'
grpc_addr = 'http://tasks.lb_neutron:8003'
event_source = { mode = 'push', url = 'ws://tasks.lb_neutron:8000/websocket', batch_delay = '500ms' }
rpc_timeout = "30s"
trusted_node = false
account_prefix = "neutron"
key_name = "neutron"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 300000
max_gas = 1000000
gas_multiplier = 1.2
max_msg_num = 20
max_tx_size = 2097152
max_grpc_decoding_size = 33554432
clock_drift = "15s"
max_block_time = "10s"
trusting_period = '13days'
ccv_consumer_chain = false
#ccv_consumer_chain = true
memo_prefix = ""
sequential_batch_tx = false
compat_mode = '0.37'
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 0.6, denom = 'untrn' }
address_type = { derivation = 'cosmos' }

[chains.packet_filter]
policy = "allow"
list = [
    ["transfer", "channel-36"],
]

[[chains]]
id = "phoenix-1"
type = "CosmosSdk"
rpc_addr = "http://tasks.lb_terra2:8000"
grpc_addr = "http://tasks.lb_terra2:8003"
rpc_timeout = "10s"
trusted_node = false
account_prefix = "terra"
key_name = "terra2"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 100000
max_gas = 400000
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
clock_drift = "5s"
max_block_time = "30s"
trusting_period = '14days' # check this
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false
event_source = { mode = 'push', url = 'ws://tasks.lb_terra2:8000/websocket', batch_delay = '500ms' }
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 0.015, denom = 'uluna' }

[chains.packet_filter]
policy = "allow"
list = [
    ["transfer", "channel-216"],
]

[[chains]]
id = "cosmoshub-4"
type = "CosmosSdk"
rpc_addr = 'http://tasks.lb_cosmoshub:8000'
grpc_addr = 'http://tasks.lb_cosmoshub:8003'
rpc_timeout = "30s"
trusted_node = false
account_prefix = "cosmos"
key_name = "cosmoshub"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 180000
max_gas = 2500000
gas_multiplier = 2
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
clock_drift = "1000s"
max_block_time = "10s"
trusting_period = '14days'
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false
compat_mode = '0.34'
event_source = { mode = 'push', url = 'ws://tasks.lb_cosmoshub:8000/websocket', batch_delay = '500ms' }
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 0.01, denom = 'uatom' }
address_type = { derivation = 'cosmos' }

[chains.packet_filter]
policy = "allow"
list = [
    ["transfer", "channel-277"],
]

[[chains]]
id = "osmosis-1"
type = "CosmosSdk"
rpc_addr = 'http://tasks.lb_osmosis:8000'
grpc_addr = 'http://tasks.lb_osmosis:8003'
rpc_timeout = "30s"
trusted_node = false
account_prefix = "osmo"
key_name = "osmosis"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 300000
max_gas = 20000000
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
clock_drift = "100s"
max_block_time = "10s"
trusting_period = '224hours'
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false
compat_mode = '0.37'
event_source = { mode = 'push', url = 'ws://tasks.lb_osmosis:8000/websocket', batch_delay = '500ms' }
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 0.003, denom = 'uosmo' }
address_type = { derivation = 'cosmos' }

[chains.packet_filter]
policy = "allow"
list = [
   ["transfer", "channel-143"],
]