[global]
log_level = 'error'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 0
clear_on_start = true
tx_confirmation = false

[rest]
enabled = false
host = '127.0.0.1'
port = 3000

[telemetry]
enabled = true
host = '0.0.0.0'
port = 3001

[[chains]]
id = "pacific-1"
type = "CosmosSdk"
rpc_addr = 'http://tasks.lb_sei:8000'
grpc_addr = 'http://tasks.lb_sei:8003'
websocket_addr = 'ws://tasks.lb_sei:8000/websocket'
rpc_timeout = "30s"
account_prefix = "sei"
key_name = "sei"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 100000
max_gas = 1000000
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 180000
clock_drift = "5s"
max_block_time = "30s"
trusting_period = '32hours'
memo_prefix = ""
sequential_batch_tx = false
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 0.1, denom = 'usei' }
address_type = { derivation = 'cosmos' }

[chains.packet_filter]
policy = "allow"
list = [
    # sort by chain name
    ["transfer", "channel-2"], # axelar
    ["transfer", "channel-1"], # cosmoshub
    ["transfer", "channel-0"], # osmosis
    ["transfer", "channel-3"], # terra2
]

[[chains]]
id = "axelar-dojo-1"
type = "CosmosSdk"
rpc_addr = 'http://tasks.lb_axelar:8000'
grpc_addr = 'http://tasks.lb_axelar:8003'
websocket_addr = 'ws://tasks.lb_axelar:8000/websocket'
rpc_timeout = "15s"
account_prefix = "axelar"
key_name = "axelar"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 100000
max_gas = 8000000
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 180000
clock_drift = "50s"
max_block_time = "10s"
trusting_period = '112hours'
memo_prefix = ""
sequential_batch_tx = false
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 0.0075, denom = 'uaxl' }
address_type = { derivation = 'cosmos' }

[chains.packet_filter]
policy = "allow"
list = [
    ["transfer", "channel-103"], # sei
]

[[chains]]
id = "cosmoshub-4"
type = "CosmosSdk"
rpc_addr = 'http://tasks.lb_cosmoshub:8000'
grpc_addr = 'http://tasks.lb_cosmoshub:8003'
websocket_addr = 'ws://tasks.lb_cosmoshub:8000/websocket'
rpc_timeout = "30s"
account_prefix = "cosmos"
key_name = "cosmoshub"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 180000
max_gas = 2500000
gas_multiplier = 2
max_msg_num = 30
max_tx_size = 180000
clock_drift = "1000s"
max_block_time = "10s"
trusting_period = '14days'
memo_prefix = ""
sequential_batch_tx = false
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 0.01, denom = 'uatom' }
address_type = { derivation = 'cosmos' }

[chains.packet_filter]
policy = "allow"
list = [
     ["transfer", "channel-584"], # sei
]

[[chains]]
id = "osmosis-1"
type = "CosmosSdk"
rpc_addr = 'http://tasks.lb_osmosis:8000'
grpc_addr = 'http://tasks.lb_osmosis:8003'
websocket_addr = 'ws://tasks.lb_osmosis:8000/websocket'
rpc_timeout = "30s"
account_prefix = "osmo"
key_name = "osmosis"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 300000
max_gas = 20000000
gas_multiplier = 1.5
max_msg_num = 30
max_tx_size = 180000
clock_drift = "100s"
max_block_time = "10s"
trusting_period = '224hours'
memo_prefix = ""
sequential_batch_tx = false
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 0.004, denom = 'uosmo' }
address_type = { derivation = 'cosmos' }

[chains.packet_filter]
policy = "allow"
list = [
    ["transfer", "channel-782"], # sei
]

[[chains]]
id = "phoenix-1"
type = "CosmosSdk"
rpc_addr = "http://tasks.lb_terra2:8000"
grpc_addr = "http://tasks.lb_terra2:8003"
websocket_addr = 'ws://tasks.lb_terra2:8000/websocket'
rpc_timeout = "10s"
account_prefix = "terra"
key_name = "terra2"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 100000
max_gas = 800000
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 180000
clock_drift = "5s"
max_block_time = "30s"
memo_prefix = ""
sequential_batch_tx = false
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 0.015, denom = 'uluna' }

[chains.packet_filter]
policy = "allow"
list = [
    ["transfer", "channel-158"], # sei
]