chain:
    bech32_prefix: cosmos
    modules:
        - modules
        - messages
        - auth
        - bank
        - consensus
        - gov
        - mint
        - slashing
        - staking
        - distribution
        - actions
node:
    type: remote
    config:
        rpc:
            client_name: bdjuno
            address: http://tasks.lb_cosmoshub:8000
            max_connections: 20
        grpc:
            address: tasks.lb_cosmoshub:8003
            insecure: true
parsing:
    workers: 1
    listen_new_blocks: true
    parse_old_blocks: false
    parse_genesis: true
    start_height: 11984895
    average_block_time: 5s
database:
    name: bdjuno
    host: tasks.psql_cosmoshub
    port: 5432
    user: postgres
    password: mysecretpassword
    schema: public
    max_open_connections: 1
    max_idle_connections: 1
    partition_size: 100000
    partition_batch: 1000
logging:
    level: info
    format: text
pruning:
    keep_recent: 100
    keep_every: 0
    interval: 100
actions:
    port: 3000