global:
  scrape_interval: 60s # default is 1 minute

scrape_configs:
  - job_name: test
    static_configs:
      - targets: ['tasks.rl_test:3001']
  - job_name: test_clear
    static_configs:
      - targets: ['tasks.rlclear_test:8000']
  - job_name: furya
    static_configs:
      - targets: ['tasks.rl_furya:3001']
  - job_name: furya_clear
    static_configs:
      - targets: ['tasks.rlclear_furya:8000']
  - job_name: coreum
    static_configs:
      - targets: ['tasks.rl_coreum:3001']
  - job_name: coreum_clear
    static_configs:
      - targets: ['tasks.rlclear_coreum:8000']
  - job_name: whitewhale
    static_configs:
      - targets: ['tasks.rl_whitewhale:3001']
  - job_name: whitewhale_clear
    static_configs:
      - targets: ['tasks.rlclear_whitewhale:8000']
  - job_name: sei
    static_configs:
      - targets: ['tasks.rl_sei:3001']
  - job_name: sei_clear
    static_configs:
      - targets: ['tasks.rlclear_sei:8000']
  - job_name: kava
    static_configs:
      - targets: ['tasks.rl_kava:3001']
  - job_name: kava_clear
    static_configs:
      - targets: ['tasks.rlclear_kava:8000']
  - job_name: composable
    static_configs:
      - targets: ['tasks.rl_composable:3001']
  - job_name: composable_clear
    static_configs:
      - targets: ['tasks.rlclear_composable:8000']
  - job_name: osmosis
    static_configs:
      - targets: ['tasks.rl_osmosis:3001']
  - job_name: osmosis_clear
    static_configs:
      - targets: ['tasks.rlclear_osmosis:8000']
  - job_name: injective
    static_configs:
      - targets: ['tasks.rl_injective:3001']
  - job_name: injective_clear
    static_configs:
      - targets: ['tasks.rlclear_injective:8000']
