${INC_GLOBAL}

[[chains]]
id = "centauri-1"
${INC_CENTAURI_1}
[chains.packet_filter]
policy = "allow"
list = [
    # sort by chain_id
    ['transfer', 'channel-13'], # agoric-3
    ['transfer', 'channel-0'],  # chihuahua-1
    ['transfer', 'channel-4'],  # cosmoshub-4
    ['transfer', 'channel-11'], # crescent-1
    ['transfer', 'channel-12'], # canto_7700-1
    ['transfer', 'channel-7'],  # evmos_9001-2
    ['transfer', 'channel-8'],  # juno-1
    ['transfer', 'channel-18'], # neutron-1
    ['transfer', 'channel-3'],  # osmosis-1
    ['transfer', 'channel-9'],  # quicksilver-2
#    ['transfer', 'channel-14'], # secret-4
    ['transfer', 'channel-6'],  # stargaze-1
    ['transfer', 'channel-5'],  # stride-1
    ['transfer', 'channel-20'], # umee-1
]

[chains.packet_filter.min_fees]

[[chains]]
id = "agoric-3"
${INC_AGORIC_3}
[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-55'],
]

[[chains]]
id = "chihuahua-1"
${INC_CHIHUAHUA_1}
[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-62'],
]

[[chains]]
id = "cosmoshub-4"
${INC_COSMOSHUB_4}
[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-617'],
]

[[chains]]
id = "crescent-1"
${INC_CRESCENT_1}
[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-64'],
]

[[chains]]
id = "canto_7700-1"
${INC_CANTO_7700_1}
[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-23'],
]

[[chains]]
id = "evmos_9001-2"
${INC_EVMOS_9001_2}
[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-82'],
]

[[chains]]
id = "juno-1"
${INC_JUNO_1}
[chains.packet_filter]
policy = "allow"
list = [
   ['transfer', 'channel-280']
]

[[chains]]
id = "neutron-1"
${INC_NEUTRON_1}
[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-17'],
]

[[chains]]
id = "osmosis-1"
${INC_OSMOSIS_1}
[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-1279']
]

[[chains]]
id = "quicksilver-2"
${INC_QUICKSILVER_2}
[chains.packet_filter]
policy = "allow"
list = [
   ['transfer', 'channel-94']
]

#[[chains]]
#id = "secret-4"
#${INC_SECRET_4}
#[chains.packet_filter]
#policy = "allow"
#list = [
#    ['transfer', 'channel-80'],
#]

[[chains]]
id = "stargaze-1"
${INC_STARGAZE_1}
[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-184'],
]

[[chains]]
id = "stride-1"
${INC_STRIDE_1}
[chains.packet_filter]
policy = "allow"
list = [
    ["transfer", "channel-134"],
]

[[chains]]
id = "umee-1"
${INC_UMEE_1}
[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-99'],
]
