${INC_GLOBAL}

[[chains]]
id = "furya-1"
${INC_FURYA_1}
[chains.packet_filter]
policy = "allow"
list = [
    ["transfer", "channel-7"], # juno
    ["transfer", "channel-6"], # osmosis
    ["transfer", "channel-1"], # terra2
    ["transfer", "channel-4"], # noble
    ["transfer", "channel-5"], # cosmoshub
    ["transfer", "channel-0"], # kujira
]

[[chains]]
id = "cosmoshub-4"
${INC_COSMOSHUB_4}
[chains.packet_filter]
policy = "allow"
list = [
    ["transfer", "channel-747"], # furya
]

[[chains]]
id = "juno-1"
${INC_JUNO_1}
[chains.packet_filter]
policy = "allow"
list = [
    ["transfer", "channel-524"], # furya
]

[[chains]]
id = "noble-1"
${INC_NOBLE_1}
[chains.packet_filter]
policy = "allow"
list = [
    ["transfer", "channel-42"], # furya
]

[[chains]]
id = "osmosis-1"
${INC_OSMOSIS_1}
[chains.packet_filter]
policy = "allow"
list = [
    ["transfer", "channel-19194"], # furya
]

[[chains]]
id = "phoenix-1"
${INC_PHOENIX_1}
[chains.packet_filter]
policy = "allow"
list = [
    ["transfer", "channel-271"], # furya
]

[[chains]]
id = "kaiyo-1"
${INC_KAIYO_1}
[chains.packet_filter]
policy = "allow"
list = [
    ["transfer", "channel-119"], # furya
]

