[global]
log_level = "info"

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = false
auto_register_counterparty_payee = false

[rest]
enabled = false
host = "127.0.0.1"
port = 3000

[telemetry]
enabled = false
host = "127.0.0.1"
port = 3001

[telemetry.buckets.latency_submitted]
start = 500
end = 20000
buckets = 10

[telemetry.buckets.latency_confirmed]
start = 1000
end = 30000
buckets = 10

[[chains]]
id = "wormchain"
type = "CosmosSdk"
rpc_addr = 'https://tncnt-eu-wormchain-main-01.rpc.p2p.world'
grpc_addr = 'http://tncnt-eu-wormchain-main-01-grpc.rpc.p2p.world'
rpc_timeout = "10s"
trusted_node = false
account_prefix = "wormhole"
key_name = "gateway"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 0
max_gas = 10000000
gas_multiplier = 1.2
max_msg_num = 4
max_tx_size = 2097152
max_grpc_decoding_size = 33554432
clock_drift = "45s"
max_block_time = "30s"
ccv_consumer_chain = false
memo_prefix = "relayed by Notional.Ventures"
sequential_batch_tx = false
event_source = { mode = 'push', url = 'wss://tncnt-eu-wormchain-main-01.rpc.p2p.world/websocket', batch_delay = '500ms' }
trust_threshold = { numerator = '2', denominator = '3' }
gas_price = { price = 0, denom = 'utest' }
address_type = { derivation = 'cosmos' }

[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-5'], # evmos
]

[[chains]]
id = "evmos_9001-2"
type = "CosmosSdk"
rpc_addr = 'http://tasks.lb_evmos:8000'
grpc_addr = 'http://tasks.lb_evmos:8003'
rpc_timeout = "30s"
trusted_node = false
account_prefix = "evmos"
key_name = "evmos"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 180000
max_gas = 2500000
gas_multiplier = 2
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
clock_drift = "40s"
max_block_time = "10s"
trusting_period = '224hours'
ccv_consumer_chain = false
memo_prefix = "relayed by Notional.Ventures"
sequential_batch_tx = false
event_source = { mode = 'push', url = 'ws://tasks.lb_evmos:8000/websocket', batch_delay = '500ms' }
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 0.0075, denom = 'aevmos' }
address_type = { derivation = 'ethermint', proto_type = { pk_type = '/ethermint.crypto.v1.ethsecp256k1.PubKey' } }

[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-94'],
]
